### ISSUE TITLE
CPAN Testersのエラー対応[0.02]

### ISSUE THREAD

**Issue by YoshiyukiItoh** [YoshiyukiItoh/D#10]
http://matrix.cpantesters.org/?dist=D+0.02
エラーの対応を実施します。

**Comment by yuki-kimoto** [comment]
よろしくお願いします。

**Comment by YoshiyukiItoh** [comment]
失敗パターン１
Dumperで出力した末尾に"."が付かない。
http://www.cpantesters.org/cpan/report/7b692de0-2425-11ea-9066-e374b0ba08e8
#   Failed test at t/test.t line 37.
#                   '{
#   'hira' => 'Ã£ÂÂÃ£ÂÂÃ£ÂÂ',
#   'kana' => 'Ã£ÂÂ¢Ã£ÂÂ¤Ã£ÂÂ¦'
# } at t/test.t line 26
# '
#     doesn't match '(?-xism:}\sat\st/test\.t\sline 26.)'

**Comment by YoshiyukiItoh** [comment]
ここまでで対応完了見込み
https://github.com/YoshiyukiItoh/D/commit/759e9215195bddbd5583b1ef6b5a8f79436b70c7

**Comment by yuki-kimoto** [comment]
ありがとうございます。

残りは、正規表現のクォートのところです。

**Comment by YoshiyukiItoh** [comment]
正規表現クォートへの書き換えが完了しました。
全てのテストケースで書き方を統一したかったため、横並びで対応しました。
https://github.com/YoshiyukiItoh/D/commit/1fb925a9703303ae8cabbf457115ccfd79ad455a

**Comment by YoshiyukiItoh** [comment]
対応完了のためクローズします。
http://matrix.cpantesters.org/?dist=D+0.03
