### ISSUE TITLE
関数追加(dxstr)

### ISSUE THREAD

**Issue by YoshiyukiItoh** [YoshiyukiItoh/D#11]
以下の関数を追加し、既存処理へ組み込みます。
・dustr
・dwstr
・dnstr

**Comment by YoshiyukiItoh** [comment]
dxstr関数について
- 既存処理をdx関数から移動させます。
- エンコード処理あとの文字列を返します。

dx関数について
- dxstrを呼び出し、返り値を標準エラー出力へ出力します。

**Comment by YoshiyukiItoh** [comment]
- [ ] エラーで取得される行数が変わらないか

**Comment by YoshiyukiItoh** [comment]
dxstr関数はexportし、単独で呼べるようにする
- dx関数を呼んだ場合は、dxstr関数の結果を標準エラー出力へ
- dxstr関数を呼んだ場合は、エンコードした文字列をreturnします

**Comment by yuki-kimoto** [comment]
dxstr関数を呼んだ場合は、エンコードした文字列をreturnします

dustrの場合は、UTF-8にエンコードした文字を、dwstrの場合は、cp932にエンコードした文字列を、dnstrの場合は、エンコードしない文字列をreturnします。

**Comment by YoshiyukiItoh** [comment]
関数分けが完了しています。
ご確認お願いいたします。
6e2a2f281d531f30ca8a03b5c55830555ccd23d1

**Comment by YoshiyukiItoh** [comment]
https://metacpan.org/pod/D
0.04としてリリースしたためクローズします。
