### ISSUE TITLE
ドキュメントの修正点

### ISSUE THREAD

**Issue by yuki-kimoto** [YoshiyukiItoh/D#12]
SYNOPSYSもdu,dw,dnを前に持ってくる。

https://github.com/YoshiyukiItoh/D/blob/master/lib/D.pm#L156

```
  # Encode all strings in reference data to UTF-8 and Dump the result to STDERR
  my $str = du $data;
```

間違ってmasterを見てました。branchを見ます。

**Comment by yuki-kimoto** [comment]
dustr,dwstr,dnstrの解説に、This function is called by du functionの代わりに、文字列が返ってくるという解説がほしいですね。

printの代わりに、戻り値を代入演算子で受け取っているほうがよいですね。

**Comment by yuki-kimoto** [comment]
use D; du $ppp;

の空白をとる

use D;du $ppp;

以上です。

use D;du

**Comment by YoshiyukiItoh** [comment]
updatedocブランチで修正入れました。
ご確認お願いいたします。

- dustr,dwstr,dnstrの解説に、This function is called by du functionの代わりに、文字列が返ってくるという解説に変更する。

- printの代わりに、戻り値を代入演算子で受け取るように変更する。

- use D;du $ppp;のように空白を削除する。

https://github.com/YoshiyukiItoh/D/blob/27c9bf00994dc7967493166489395703dc3d4490/lib/D.pm

**Comment by yuki-kimoto** [comment]
ばっちりです!

**Comment by YoshiyukiItoh** [comment]
ありがとうございます。0.05としてリリースします。

**Comment by YoshiyukiItoh** [comment]
クローズします。

**Comment by yuki-kimoto** [comment]
リリースしたら教えていただくことは可能でしょうか?

**Comment by YoshiyukiItoh** [comment]
失礼しました。リリースしました。
