### ISSUE TITLE
キーの並べ替えなど

### ISSUE THREAD

**Issue by yuki-kimoto** [YoshiyukiItoh/D#3]
duとdw関数ですが、次の三つの機能を追加してください。

・Data::Dumperをオブジェクト指向インターフェースで使う
・キーをソートします。
・$VAR1をなくします
・インデントを0にします

https://metacpan.org/pod/Data::Dumper

Data::Dumperのオプションで指定できます。

**Comment by yuki-kimoto** [comment]
warn関数で、行番号を出力する。

warn関数の文字列が改行ですが、これを取り除くと、ファイル名と行番号が表示されるようになります。

**Comment by YoshiyukiItoh** [comment]
warn関数から改行削除しましたが、行番号やファイル名が出力されていないようです。
確認方法は別にありますでしょうか？
ソース：
https://github.com/YoshiyukiItoh/D/commit/7d5eb71be2d9444bf8eae85f275cb367e17dd728

参考：
https://tutorial.perlzemi.com/blog/20100213126425.html

**Comment by yuki-kimoto** [comment]
Dumperの末尾に改行が入っているのかもしれません。

chompを使って、これを削除してあげるとうまくいくかも。

**Comment by YoshiyukiItoh** [comment]
ありがとうございます。
うまくいきました。

**Comment by yuki-kimoto** [comment]
こちらですが、グローバルに設定している部分があるので、ローカルに設定してみましょう。

**Comment by YoshiyukiItoh** [comment]
完了しました。
https://github.com/YoshiyukiItoh/D/commit/837bbbfccd3dc97f6068b2ec9d39123a1a188165

**Comment by YoshiyukiItoh** [comment]
コードリファレンスが、例外をはかないことはテストで確認しています。
テストでコードリファレンスが関数に渡された際にDumperの標準でsub { "DUMMY" }と出ることを確認しています。
・$Data::Dumper::Deparseを使用して中身が見えた方がよいでしょうか。
　→変数名を日本語とすることが可能とはいえ、あえてdu,dw,dnする理由がないかなとは考えています。
・DモジュールにもDumper関連のオプションを変更するインターフェースを用意して切り替えられるとよいかなとも考えています。（現在のTerse=1,Sortkeys=1,Indent=1がDモジュールのデフォルト）
　Dump用のためですが、一部用意すると他オプションもとなるため悩ましいです。

**Comment by yuki-kimoto** [comment]
・$Data::Dumper::Deparseを使用して中身が見えた方がよいでしょうか。

サブルーチンの中身は見えなくても、困ることが少ないので、大丈夫です。

**Comment by yuki-kimoto** [comment]
>・DモジュールにもDumper関連のオプションを変更するインターフェースを用意して切り替えられるとよいかなとも考えています。

僕自身の用途としては、なくても大丈夫ですが、

伊藤さんが、希望する場合は、第二引数などにして、オプションを渡せるのもよいかと思います。

**Comment by yuki-kimoto** [comment]
実装が完了しているので、closeします。
