### ISSUE TITLE
試験を詳細化

### ISSUE THREAD

**Issue by yuki-kimoto** [YoshiyukiItoh/D#6]
・正規表現を使って、マッチさせる
・スカラリファレンス・コードリファレンスが例外をはかない

**Comment by YoshiyukiItoh** [comment]
以下のdn関数のテストでうまく正規表現マッチできておらず、どのように考えて進めれば良いでしょうか？
【テストコード】
https://github.com/YoshiyukiItoh/D/blob/dntest/t/test.t
【コマンドライン】
[yoshi@mbp17 t]$ perl -Mblib test.t 
ok 1
ok 2
ok 3
ok 4
not ok 5
#   Failed test at test.t line 73.
#                   '{
#   'hira' => "\x{3044}\x{3068}\x{3046}",
#   'kanji' => "\x{4f0a}\x{85e4}"
# } at /Users/yoshi/work/perl_work/D/t/../blib/lib/D.pm line 48.
# '
#     doesn't match '(?^u:\s\s\'hira\'\s=>\s"\x{3044}\x{3068}\x{3046}",)'
not ok 6
#   Failed test at test.t line 76.
#                   '{
#   'hira' => "\x{3044}\x{3068}\x{3046}",
#   'kanji' => "\x{4f0a}\x{85e4}"
# } at /Users/yoshi/work/perl_work/D/t/../blib/lib/D.pm line 48.
# '
#     doesn't match '(?^u:\s\s\'kanji\'\s=>\s"\x{4f0a}\x{85e4}")'
1..6
# Looks like you failed 2 tests of 6.
[yoshi@mbp17 t]$

**Comment by yuki-kimoto** [comment]
エンコードしないという条件ですので、まず試験データは、エンコードしたものを用意する必要があります。

```
my $date = {
  foo => encode('UTF-8', 'あいう');
}
```

みたいな感じですね。

**Comment by yuki-kimoto** [comment]
carpで、正しく行番号とファイル名が出力されていることの確認も必要になりました。

**Comment by yuki-kimoto** [comment]
Perlでは、__LINE__で行番号がとれます。行番号の試験が大変そうだったので、差し替えておきました。
